# Generated by Django 5.1.4 on 2025-01-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(max_length=60)),
                ('Vehicle_company', models.CharField(max_length=60)),
                ('Vehicle_color', models.CharField(max_length=20)),
                ('Vehicle_image1', models.ImageField(upload_to='img/Vehicle_images/')),
                ('Vehicle_image2', models.ImageField(upload_to='img/Vehicle_images/')),
                ('Vehicle_image3', models.ImageField(upload_to='img/Vehicle_images/')),
                ('Vehicle_description', models.CharField(max_length=1500)),
                ('Vehicle_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=60)),
                ('customer_lastname', models.CharField(max_length=60)),
                ('customer_address', models.CharField(max_length=600)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=32)),
                ('customer_dob', models.DateField()),
                ('customer_mobileno', models.CharField(max_length=10)),
                ('customer_license', models.ImageField(upload_to='img/Customer_License/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
